train:
  epochs: 1
  iterations: 10
  text: "Sun in the grass"

models:
  vqgan:
    lr: 0.1
    model_download_path: 'https://heibox.uni-heidelberg.de/f/140747ba53464f49b476/?dl=1'
    model_config: "configs/vqgan/model-1024.yaml"
    model_ckpt: "models/vqgan/last-1024.ckpt"
    model_name: "ViT-B/32"
    model_size: 1024
    sideX: 200
    sideY: 200
    sync: 0.
    samples: 1
    save_freq: 1
    overscan: False
    upload_image: False
