train:
  epochs: 1
  iterations: 10
  text: "Dog in the fog"
models:
  vqgan:
    model_config: "/home/mdomagala/Pulpit/gans-clip-pw/configs/vqgan/model-1024.yaml"
    model_ckpt: "/home/mdomagala/Pulpit/gans-clip-pw/models/vqgan/last-1024.ckpt"